// Íconos de la app (Iconify, set Material Design Icons).
// Si se pasa a modo offline, solo hay que cambiar este archivo.
export const ICONOS = {
  lista: "mdi:clipboard-text-outline",
  carnet: "mdi:card-account-details-outline",
  reloj: "mdi:clock-outline",
  aviso: "mdi:alert-outline",
  camara: "mdi:camera-outline",
  exito: "mdi:check-circle",
  error: "mdi:close-circle",
  cargando: "mdi:timer-sand",
  info: "mdi:information-outline",
  cerrar: "mdi:close",
  menu: "mdi:menu",
  usuario: "mdi:account-circle-outline",
  panel: "mdi:view-dashboard-outline",
  empleados: "mdi:account-group-outline",
  departamentos: "mdi:domain",
  cargos: "mdi:badge-account-horizontal-outline",
  asistenciaHoy: "mdi:calendar-check-outline",
  historico: "mdi:history",
  matricula: "mdi:school-outline",
  blog: "mdi:newspaper-variant-outline",
  reportes: "mdi:chart-box-outline",
};
